export default {
    LOGIN: 'LOGIN',
    GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
    GET_MOVIES_REQUEST_SUCCESS: 'GET_MOVIES_REQUEST_SUCCESS',
    GET_MOVIES_REQUEST_FAILURE: 'GET_MOVIES_REQUEST_FAILURE',
    FETCH_TODO_REQUEST: 'FETCH_TODO_REQUEST',
    FETCH_TODO_SUCCESS: 'FETCH_TODO_REQUEST_ACCESS',
    FETCH_TODO_FAILURE: 'FETCH_TODO_REQUEST_FAILURE',
    SORT_TODOS_BY_STATUS: 'SORT_TODOS_BY_STATUS'
}